### ISSUE TITLE
Bower.json file doesn't have dependencies

### ISSUE THREAD

**Issue by nWidart** [troolee/gridstack.js#113]
Hello,

You state in the readme file you have dependencies, but the bower.json file doesn't have those.
Thus when installing gridstack with bower, it doesn't install the dependencies with it.

``` json
"lodash": "~3.6.0",
"jquery-ui": "~1.11.4"
```

**Comment by PierreReliquet** [comment]
When installing gridstack through bower it installs the version 0.2.2 which does not have any bower.json file and does not require lodash but : 

* [underscore.js](http://underscorejs.org) (>= 1.7.0)
* [jQuery](http://jquery.com) (>= 1.11.0)
* [jQuery UI](http://jqueryui.com) (>= 1.11.0). Minimum required components: Core, Widget, Mouse, Draggable, Resizable

So because there is no bower.json file, I believe you should add it manually.

**Comment by nWidart** [comment]
That's why I did yes. I see in version 2.3 their are requirements defined correctly.
