### ISSUE TITLE
Fixed position grid with 100% window height

### ISSUE THREAD

**Issue by Dimosthenis** [troolee/gridstack.js#118]
First of all thank you for this useful plugin and for your hard work.

I need to create a responsive layout horizontally and vertically in full window size.
The reason I need it "full-screen" is because of the grid items which should respond on click
events and change position to all 4 edges of the screen randomly.

I changed grid-stack container to 100% width and height and added some css with data attributes like
"data-gs-y" top (position) and "data-gs-height" with percentage but It is not working as smooth I hoped
because in window resizes some items overlap

Thank you again, I hope you understand what I'm trying to accomplish

**Comment by Dimosthenis** [comment]
I managed to create squares by giving cell_height equal to cell_width.
Its not pixel perfect by the difference is 1 or 2 pixels.

Another think Im trying is creating smaller grid size. I used the sass script provided and works ok on all cell widths except 1x1.

I created a 24 and a 20 size grid but in both cases the cell with data-width 1 and data-height 1 always displays the width larger than the height.
The grid-stack's height is left blank in order to have as many rows as needed but it ain't working.

Could you pls give me a hint or a working example with larger grid and smaller 1x1 cells?

Thanks

**Comment by alangunning** [comment]
+1 for supporting cell_height as percentages

**Comment by stefan-schweiger** [comment]
+1

**Comment by nkotha** [comment]
+1

**Comment by radiolips** [comment]
It makes more sense for the user to manage this. In order to get the 100% height you're referring to, @Dimosthenis , you can simply take the height and divide it by whatever you'd like before passing a `cellHeight` to gridstack. This would work for initial load, but obviously would not be responsive. Now, if you change page size after that, gridstack fires resize events, and these could be used to modify the height or width of the content. I'm personally doing this in my project for some widgets but not for others - which is precisely why it shouldn't be part of the core.
