### ISSUE TITLE
Problems removing widgets

### ISSUE THREAD

**Issue by davidwieler** [troolee/gridstack.js#137]
using code `var grid = $('.grid-stack').data('gridstack');grid.remove_widget('#grid-stack-item-153');` This id has been added to the widget on creation doesn't work for me, it throws error: "Cannot set property '_id' of undefined on line 271 of gridstack.js"

Is there a different way to remove the widgets? Or is there a certain (el) to pass?

**Comment by abologna-r7** [comment]
it expects a DOM element. Please try:

```javascript
grid.remove_widget($('#grid-stack-item-153'));
```

**Comment by davidwieler** [comment]
Thanks! For anyone that may find this and have the same issues:
I added the widget item, and append a remove item to the div.
Then just used:
`grid.remove_widget($(this).parents().eq(1));`
and it worked great.

**Comment by KevinSimple** [comment]
@davidwieler , you got the wrong solution mate,$(this).parents().eq(1) means you select your second parent div, then accidentally, it works.
the real issue is with the code in gridstack.js, line 736 '  el = $(el);' , it's reselcting the element you passing through, in this case, dont folow the DOC, just do grid.remove_widget('#grid-stack-item-153');
it works with robustly.

**Comment by tarunigattu1992** [comment]
Hey,

Cant we just do it this way:

               this.grid = $('.grid-stack').data('gridstack');
	      this.add = function(){
	     this.grid.addWidget($('<div><div class="grid-stack-item-content" /><button type="button" class="close" aria-label="Close" id="removewidget" ><span aria-hidden="true">&times;</span></button><div/>'),5,0,2,2);
 $('.close').click(this.removeWid);
}.bind(this);
			
		  
 this.removeWid = function(e){
 e.target.closest("div").remove();  // closest div is the widget to be removed 
 }
