### ISSUE TITLE
default resize handle icon broken

### ISSUE THREAD

**Issue by mikehaas763** [troolee/gridstack.js#198]
The drag handle icon does not render correctly. I've uploaded a screenshot of what it looks like.

![image](https://cloud.githubusercontent.com/assets/2096573/9012237/45485fdc-3781-11e5-89f0-17ed9724cb2d.png)

I'm trying to set up a very basic working example of gridstack. I have lodash, jquery, jquery-ui, gridstack, jquery-ui.css, and gridstack.css referenced in my page.

```html
<div class="grid-stack">
    <div class="grid-stack-item"
         data-gs-x="0" data-gs-y="0"
         data-gs-width="4" data-gs-height="2">
        <div class="grid-stack-item-content"></div>
    </div>
    <div class="grid-stack-item"
         data-gs-x="4" data-gs-y="0"
         data-gs-width="4" data-gs-height="4">
        <div class="grid-stack-item-content"></div>
    </div>
</div>
<script>
    var options = {
        animate: true,
        cell_height: 80,
        vertical_margin: 10
    };

    $('.grid-stack').gridstack(options);
</script>
```

Am I missing anything?

**Comment by h-nazzal** [comment]
yes i belive the project is using font awesome for the icon ... 
so you need to have that included as well ... 
this is another thing that needs to be addressed a css triangle would do the trick in here or even an svg .. but not the whole font awesome !!! even boot strap icons would make more sense .

**Comment by mikehaas763** [comment]
@h-nazzal That makes sense, didn't realize that font awesome was used. At least I can override that and use my own (I think). I agree though typically what I would have done is base64 encoded an svg.

I saw the issue you created #195 with suggestions and I agree with all of those points. It's why I initially began prototyping my own grid mikehaas763/salty-grid a couple of months ago based on ES6. It would be nice though if I didn't have to start from scratch as that could take me months to finish just basing it off of my free time.

**Comment by h-nazzal** [comment]
here is a qiuick fix 
```less
        > .ui-resizable-se,
        > .ui-resizable-sw {
            &:after{
                content :' ';
                display: block;
                width: 0; 
                height: 0; 
                border-left: 5px solid transparent;
                border-right: 5px solid transparent;
                border-bottom: 5px solid black;
                filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1);
                .vendor(transform, rotate(135deg));
            }
        }
        
        > .ui-resizable-se {
            display: inline-block;
        }
```

**Comment by mikehaas763** [comment]
I added in font-awesome just to see what would happen. Now I see the correct font icon, but something is still not rendered right.

![image](https://cloud.githubusercontent.com/assets/2096573/9013634/35423590-378b-11e5-97e2-650f487c8b0e.png)

**Comment by h-nazzal** [comment]
could you inspect that and see what element is being "miss rendered"

**Comment by mikehaas763** [comment]
Yep. I already inspected it and tried look at the styling but still can't figure out what's wrong.

```html
<div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90; /* display: none; */"></div>
```

**Comment by h-nazzal** [comment]
aha ok i got it ...
jquery-ui.css just remove that and you'll be good thats just the icon from the jquery-ui styling file

**Comment by h-nazzal** [comment]
side note rename the issue to "resize handle"

**Comment by mikehaas763** [comment]
That was it, thanks.

**Comment by derekm** [comment]
I'm not sure this should be closed. "Remove jQuery UI CSS" is not a good solution for everyone. A more general solution should be found for those who can't disable jQuery UI CSS.

**Comment by h-nazzal** [comment]
you have to disable either the jqueryui css or remove the font awesome icon .. which ever you see fit ...  this is currently a bug ! so it's not something that is supposed to happen

**Comment by derekm** [comment]
This CSS rule added to gridstack.css removes the jQuery UI handle:

    .ui-icon {
      background-image: none;
    }

**Comment by h-nazzal** [comment]
well thank you for sharing this. but in reality what should be removed is the font-awesome icon not the other way around. a small triangle would deliver the message just fine.

**Comment by pySilver** [comment]
Oh guys, dont invent a problem where its not. Just ovveride an icon or whatever you want in your css. 



Dnia 8 sie 2015 o godz. 02:02 H.Nazzal <notifications@github.com> napisał(a):

**Comment by h-nazzal** [comment]
@pySilver it's not an invention ... there is a problem. but it's no big deal to fix.

**Comment by derekm** [comment]
I don't mind the FontAwesome dependency. I can understand that others might not want it. It would be nice if gridstack had more of a build system or at least a conventional way to optionally exclude certain deps or features.

A safer CSS rule for inclusion in gridstack.css is:

    .grid-stack-item > .ui-icon.ui-resizable-handle {
      background-image: none;
    }

It is smart for gridstack to not having conflicting resources/dependencies out-of-the-box.

**Comment by pySilver** [comment]
For just 2 icons (drag & resize) itd be much easier to use raw svg embedded into css. If one is aware about browser compatibility - then one should overfide this css with png fallback. Everyone else would have dependency free icons.



Dnia 10 sie 2015 o godz. 16:09 Derek P. Moore <notifications@github.com> napisał(a):

**Comment by h-nazzal** [comment]
@pySilver we already know the browser compatibility this plugin depends on jquery-ui heavily  1.11.x which means IE 8+ is the browser support target.

**Comment by randoum** [comment]
Here are the problems I can think of with the default resize handle implementation:

1)
It displays the default jQuery-ui handle through the css class `ui-icon ui-icon-gripsmall-diagonal-se`. See https://github.com/jquery/jquery-ui/blob/1.11.4/ui/resizable.js#L183
So it will load and display jQuery-ui icons file defined in theme.css 
*Note: They modified this method in the master branch, so it may change in next release*

2) 
At the same time it also display the FontAwesome icon through the css class `.grid-stack > .grid-stack-item > .ui-resizable-se` and `.grid-stack > .grid-stack-item > .ui-resizable-nw` defined by gridstack.js CSS
Some of us already use FontAwesome and don't need to redefine its CSS classes, and other don't use it and would like to freely chose the icon library. 

3) 
gridstack.js defines the css classes `ui-resizable-{direction}` css classes. On the other hand, jQuery-ui resize handle customisation makes it mandatory to use those classes for the custom elements See http://api.jqueryui.com/resizable/#option-handles
So when you try to use custom handle by defining your own elements and css classes you are still affected by the issue above because FontAwesome icon will be displayed through `ui-resizable-{direction}` css classes.

4) 
`.grid-stack > .grid-stack-item > .ui-resizable-sw` and `.grid-stack > .grid-stack-item > .ui-resizable-se` class uses the same FontAwesome icon, but `ui-resizable-se` applies rotation on it.
It's uselessly heavy and require more css overwriting to remove this default behaviour. It would perhaps be better to work with FontAwesome team to get clean icon for the diagonal arrows.

---

To sum-up, all of this makes impossible to have a correctly displayed resize handle out-of-the-box, whatever is your set-up you'll have CSS issue(s) that need to be fixed manually. Either to eliminate jQuery icon display, either to eliminate FontAwesome icon display, or to eliminate both in order to implement your own solution. 

I suggest a clean-up. You should decide of a default solution (jQuery vs FontAwesome) that cleanly works out-of-the-box, and make it super-easy to switch to something else.

**Comment by randoum** [comment]
@mikehaas763  would you mind to reopen this issue?

Here are the problems I can think of with the default resize handle implementation:

1)
It displays the default jQuery-ui handle through the css class `ui-icon ui-icon-gripsmall-diagonal-se`. See https://github.com/jquery/jquery-ui/blob/1.11.4/ui/resizable.js#L183
So it will load and display jQuery-ui icons file defined in theme.css 
*Note: They modified this method in the master branch, so it may change in next release*

2) 
At the same time it also display the FontAwesome icon through the css class `.grid-stack > .grid-stack-item > .ui-resizable-se` and `.grid-stack > .grid-stack-item > .ui-resizable-nw` defined by gridstack.js CSS
Some of us already use FontAwesome and don't need to redefine its CSS classes, and other don't use it and would like to freely chose the icon library. 

3) 
gridstack.js defines the css classes `ui-resizable-{direction}` css classes. On the other hand, jQuery-ui resize handle customisation makes it mandatory to use those classes for the custom elements See http://api.jqueryui.com/resizable/#option-handles
So when you try to use custom handle by defining your own elements and css classes you are still affected by the issue above because FontAwesome icon will be displayed through `ui-resizable-{direction}` css classes.

4) 
`.grid-stack > .grid-stack-item > .ui-resizable-sw` and `.grid-stack > .grid-stack-item > .ui-resizable-se` class uses the same FontAwesome icon, but `ui-resizable-se` applies rotation on it.
It's uselessly heavy and require more css overwriting to remove this default behaviour. It would perhaps be better to work with FontAwesome team to get clean icon for the diagonal arrows.

---

To sum-up, all of this makes impossible to have a correctly displayed resize handle out-of-the-box, whatever is your set-up you'll have CSS issue(s) that need to be fixed manually. Either to eliminate jQuery icon display, either to eliminate FontAwesome icon display, or to eliminate both in order to implement your own solution. 

I suggest a clean-up. You should decide of a default solution (jQuery vs FontAwesome) that cleanly works out-of-the-box, and make it super-easy to switch to something else.

**Comment by mikehaas763** [comment]
I agree. This issue is a real issue and should remain open. The only reason I closed it was because I discovered how to solve the problem for my specific situation.

**Comment by randoum** [comment]
btw, when I say "you should decide", I was refering to @troolee

**Comment by troolee** [comment]
Replace dependency of font awesome with inline svg
