### ISSUE TITLE
Not receiving correct values from get_cell_from_pixel()

### ISSUE THREAD

**Issue by DeadlyBrad42** [troolee/gridstack.js#237]
I am attempting to use `get_cell_from_pixel()` to implement dragging and dropping items from another list to add them to my grid, but I'm not getting back the values I expect.

I'm passing in a position relative to the document, but since `get_cell_from_pixel()` internally compares that against `this.container.position()` (and since my grid is in a div with `position:relative`) the calculation is off.

From the name, I had assumed the function worked from a pixel position relative to the document. I was wondering if there was a reason you used `this.container.position()` instead of `this.container.offset()`? Or if there is, is it possible to add in an optional argument that would use `this.container.offset()`? If it's a feature you'd be interested in adding, I could implement it and create the PR myself if you'd like.

**Comment by radiolips** [comment]
@DeadlyBrad42 - apologies for the very long delay, but we're giving gridstack more attention now, and, as such, have added in the parameter you've recommended. `getCellFromPixel` now takes in an optional second parameter to use offset rather than position. Thanks for the suggestion to do this and recommendation to use offset.
