### ISSUE TITLE
Minimum width for gridstack-item

### ISSUE THREAD

**Issue by siddshenoy** [troolee/gridstack.js#270]
Currently, grid items have a minimum width as a % of the overall width. However, I need an absolute minimum in terms of pixels so that the grid item cannot be shrunk too small. What's the best way of achieving this? Thanks!

**Comment by radiolips** [comment]
The grid snaps into place and doesn't resize by-pixel, as I'm sure you're aware. Because of this, a minimum width in pixels doesn't make sense for `gridstack` to support. However, with ease you may determine this minimum width, convert the number to columns, and call `grid.minWidth()` for each widget to set its minimum width in columns. We may add a helper function to change all of the elements at once, which should help you. In the meantime, please try the fix I mention and let me know how it goes.
