### ISSUE TITLE
Reposition the items after dragging

### ISSUE THREAD

**Issue by dnascimento** [troolee/gridstack.js#314]
After drag and drop the items, I have free space between them. Is there a away to refit the items to make them compact again?

**Comment by MargoJunker** [comment]
You must change attributes in gridstack.css, Start from line 24.

**Comment by troolee** [comment]
Items should be compacted automatically if you don't use `float` option. Can you provide an example?

**Comment by dnascimento** [comment]
This is the page on initial state:
![compated](https://cloud.githubusercontent.com/assets/933984/12987990/9c3f3590-d0f6-11e5-9d8d-0a5aaa57a83e.png)

This is what happens when we expand the green:

![result](https://cloud.githubusercontent.com/assets/933984/12988013/b9b221dc-d0f6-11e5-89ce-c41815f3d80c.png)

This is the expected behaviour:
![wanted](https://cloud.githubusercontent.com/assets/933984/12988015/c17dc218-d0f6-11e5-82df-d8f89c5dbc8e.png)
: 

What is your opinion @troolee ?

**Comment by troolee** [comment]
Yes, gridstack works in your case as it's expected. And I don't think I will change that behaviour at least in the next couple of releases.

The algorithm which resolves collisions is not optimal right now and it works extremely slow on huge grids. So one of my first goal to do is rewrite with the same behaviour as it is now.

Also why red block went to the left, not to the right? Anyway the behaviour you're expecting is not trivial to implement. So probable in the future and if it will be more requests or so... But not now it's for sure.

Sorry for that.

**Comment by nelsieborja** [comment]
@troolee, we need the horizontal auto-compacting. I see compact method is already available but is there a way to do it automatically? Tried it with `grid.on("added removed change", () => grid.compact())` but doesn't work well with React.
My code is available [here on the codesandbox](https://codesandbox.io/s/gridstack-vibvy?file=/src/App.js:1218-1272). Appreciate your suggestion. Thanks

**Comment by adumesny** [comment]
troolee hasn't been involved in 3+ years.

Ironically I re-wrote the collision in 4.x and as side effect to much better heuristics is much faster now (does hit test once, re-use it through the many nested calls, only does hit with shape itself not pushing an entire row, and most if same size it's a simple swap without any further test/pushing).

I'm also the one who added the `compact()` method (seem like a handy behavior). I can't debug your code, but yeah you should be able to call this manually after the fact (might need a delay in case things happen after the callback but not done doing internal cleanup). Also might want to detect and ignore change C that will happen due to compact (should not be infinite loop as I track real changes pretty good now unlike v0.6)

don't forget to contribute if you find lib useful! it's been a ton of work and I'm not done...

**Comment by nelsieborja** [comment]
@adumesny, thanks appreciate your input. But since we kinda need this feature now and digging into its code might take a while so might just gonna do some hacky tweaking for now. Will def try to have a look at this and see what I can do.
