### ISSUE TITLE
Problem lodash 4.5.1 - collision card broken

### ISSUE THREAD

**Issue by Julienng** [troolee/gridstack.js#359]
Hi,
I work on a binding for JavaEE/JSF of gridStack for my company. I've got a problem when I use the latest version of lodash. It seems like lodash break the collision between card (but works great with 3.10.1).

![lodash4 5 1](https://cloud.githubusercontent.com/assets/8990614/13283733/e489038c-daef-11e5-819b-c2f18c26558b.png)

My code look like this for the generated html (the id of component are prepend with is parent id):

```html
<div id="mainDynTab:sandboxBean_formBody:j_id_3j_2_1_5_3" class="grid-stack" data-gs-width="12" data-gs-height="0" data-gs-animate="true">
	<div id="mainDynTab:sandboxBean_formBody:_1" class="grid-stack-item" data-widget="widget_mainDynTab_sandboxBean_formBody__1" data-gs-x="0" data-gs-y="0" data-gs-width="5" data-gs-height="4" data-gs-min-width="3" data-gs-min-height="4" data-gs-no-move="true" data-gs-no-resize="true" data-gs-auto-position="true">
		<div id="mainDynTab:sandboxBean_formBody:_1_container_content" class="grid-stack-item-content">
			<div id="mainDynTab:sandboxBean_formBody:_1_header" class="grid-stack-item-header">
				<span>
					1

				</span>
				<a id="mainDynTab:sandboxBean_formBody:_1_closer" href="#" class="grid-stack-item-header-icon">
					<span class="fa fa-times">
					</span>
				</a>
				<a id="mainDynTab:sandboxBean_formBody:_1_move" href="#" class="grid-stack-item-header-icon-disabled">
					<span class="fa fa-arrows-alt">
					</span>
				</a>
				<hr>
			</div>
			<div id="mainDynTab:sandboxBean_formBody:_1_content" class="grid-stack-item-child">
			</div>
		</div>
	</div>
	<div id="mainDynTab:sandboxBean_formBody:_2" class="grid-stack-item" data-widget="widget_mainDynTab_sandboxBean_formBody__2" data-gs-x="0" data-gs-y="0" data-gs-width="4" data-gs-height="4" data-gs-min-width="4" data-gs-min-height="4" data-gs-auto-position="true">
		<div id="mainDynTab:sandboxBean_formBody:_2_container_content" class="grid-stack-item-content" style="text-align: center;">
			<div id="mainDynTab:sandboxBean_formBody:_2_header" class="grid-stack-item-header">
				<span>2</span>
				<a id="mainDynTab:sandboxBean_formBody:_2_closer" href="#" class="grid-stack-item-header-icon">
					<span class="fa fa-times">
					</span>
				</a>
				<a id="mainDynTab:sandboxBean_formBody:_2_move" href="#" class="grid-stack-item-header-icon">
					<span class="fa fa-arrows-alt">
					</span>
				</a>
				<hr>
			</div>
			<div id="mainDynTab:sandboxBean_formBody:_2_content" class="grid-stack-item-child">
				2
			</div>
		</div>
	</div>
</div>
```

And I initialize the gridStack engine with this parameter:
```javascript
var options = {
				animate : true,
				//width : 2,
				cellHeight : 50,
				verticalMargin : '1em',
				handleClass : '.grid-stack-item-header .grid-stack-item-header-icon',
				draggable : {
					handle : '.grid-stack-item-header .grid-stack-item-header-icon',
					scroll : false,
					appendTo : 'body'
				}
			};
			$('.grid-stack').gridstack(options);
```
The Javascript developer doesn't show any error.

-----------------------
edit: doesn't have staticGrid parameter

**Comment by radiolips** [comment]
Hi there! I'll be happy to look into this. I stay up to date with lodash
for a personal project and it still seems to work. Could you confirm for me
what version of gridstack you're using?

**Comment by Julienng** [comment]
I use the last release `v0.2.4`
Thanks !

**Comment by radiolips** [comment]
`v0.2.4` is certainly the latest stable release of gridstack, but the documentation is currently for `v0.2.5-dev`, which is available from the master branch of gridstack. However, if you'd like to stay with `v0.2.4`, lodash 4.x will still work (thanks, @andrewr88 for that!). In order to get 0.2.4 working, you'll need to use the old version of the options:

```var options = {
                animate : true,
                //width : 2,
                cell_height : 50,
                vertical_margin : '1em',
                handle_class : '.grid-stack-item-header .grid-stack-item-header-icon',
                draggable : {
                    handle : '.grid-stack-item-header .grid-stack-item-header-icon',
                    scroll : false,
                    appendTo : 'body'
                }
            };
            $('.grid-stack').gridstack(options);```

The change here is that `handleClass` needs to be `handle_class`, `cellHeight` should be `cell_height`, and `verticalMargin` will need to be `vertical_margin`. Let me know if you still need help, but this should do it !

**Comment by Julienng** [comment]
Yeah that what I tried. It work great with `v0.2.5-dev`
Thank you !

**Comment by DoctaWorm** [comment]
Ugh... I'm on version 0.2.3 and we still haven't upgraded, we're trying to hold out for 0.3.0 but I just came across a bug that can be fixed with one of our features with lodash v4.x but updating that killed the  collision  

![image](https://cloud.githubusercontent.com/assets/7025044/22939914/d7b59fa2-f2a5-11e6-9bb8-921572fb9141.png)

So many cards are overlapped, I already have the old version of the options in our gridstack adapter. I guess I'll just put this feature on the backburner and tell them we'll have to wait for 0.3.0 before we can do a few requests they want. 

@radiolips @troolee Any updates on what the timeline looks for 0.3.0?
