### ISSUE TITLE
Confusing convention for resizing a widget's height

### ISSUE THREAD

**Issue by ericmux** [troolee/gridstack.js#365]
I looked into the internally generated CSS styles for the widget heights (the `.grid-stack-item[data-gs-height="x"]` classes). I'm using the API to call `resize(el, width, height)` and I expected the widget height to be resized by `(newY - oldY)*grid.cell_height()`. As can be seen from the internal stylesheets, what acutally happens is `(newY - oldY)*(grid.cell_height() + grid.vertical_margin())`, which shouldn't be the proper behavior IMO. Releavant source code below:

`            getHeight = function(nbRows, nbMargins) {
                return (self.opts.cellHeight * nbRows + self.opts.verticalMargin * nbMargins) +
                    self.opts.cellHeightUnit;`

`Utils.insertCSSRule(this._styles,
                    prefix + '[data-gs-height="' + (i + 1) + '"]',
                    'height: ' + getHeight(i + 1, i) + ';',
                    i
                );`

**Comment by ericmux** [comment]
A `grid.vertical_margin(val)` call would be a nice addition too.

**Comment by radiolips** [comment]
Hi, eric! We appreciate your concerns and love that you'd like to help make gridstack a better library.

The height that the widgets receive are, as you know, a thin formula based on its internal "height." This formula was designed intentionally, so that the widgets line up properly. I have not seen of an issue with this. I certainly understand that it's not working the way that you'd like. Could you create a small jsfiddle for me to see an example of what you'd like vs what you're currently seeing? That'd be extremely helpful.

Adding `verticalMargin(val)` is a great idea. So great, in fact, it's already been added! We didn't realize that it wasn't in the documentation, but I'll make sure it gets added shortly. Using `v0.2.5-dev`, you may call `grid.verticalMargin(val)` to change the vertical margin. So, thanks for the suggestion - I suppose you weren't the only person who could benefit from this feature!

**Comment by radiolips** [comment]
`verticalMargin` has been added to the documentation. I'm closing this out, but please feel free to reopen it if you have more information about the height issue.
