### ISSUE TITLE
difference with gridser?

### ISSUE THREAD

**Issue by StevenFlecha** [troolee/gridstack.js#390]
Hi,

Excuse my ignorance but on your site you write "responsive bootstrap v3 friendly layouts" but how?

In none of the examples you actually make use of any bootstrap classes. You add it to head but if you do that with gridster it works exactly the same..

What does gridstack do different then gridster?

Reason I'm asking is because I have bootstrap HTML templates I want to put them in the grid so users can move it all around .. then when done have a normal html page (without the draggable grid). I thought gridstack would help to do that in favor of gridster but so far I have not seen any difference between the 2..

Thanks!

**Comment by Julienng** [comment]
Hi,
these [example](http://troolee.github.io/gridstack.js/demo/two.html) load bootstrap.
I choose gridstack because gridster is no longer support by his creator. That why I choose gridstack.
For the difference, I think both reach the same goal but I let that for someone better.

**Comment by troolee** [comment]
We never declare that gridstack uses bootstrap classes. We say that gridstack could be responsive (widgets are not fixed width) it works well on bootstrap 3 pages with fixed or responsive layout. That's why it says bootstrap 3 *friendly*.

It wasn't a goal for gridstack to create bootstrap 3 layouts. It's not a goal now neither. The goal of gridstack is to create dashboard layouts with draggable/resizable widgets.

Gridstack uses internal grid to implement its logic. DOM nodes are just interpretation of this grid. So we or you probably could create a thirty part library which exports this internal grid into bootstrap 3/bootstrap 4/absolute divs/whatever layout. But I don't see this as part of gridstack core. As the same as support of angular/knockout/whatever libraries. We're doing all necessary for smooth support but it will never be a part of core.

The main idea is to build as simple and flexible lib as possible.

**Comment by StevenFlecha** [comment]
ok, thanks that clarifies!
