### ISSUE TITLE
Media query conflict

### ISSUE THREAD

**Issue by Skulmuk** [troolee/gridstack.js#415]
I'm deploying an app utilising Bootstrap 3 and GridStack to a **Samsung Galaxy Tab A** and it seems that [this line](https://github.com/troolee/gridstack.js/blob/master/src/gridstack.scss#L128) kills the grid display and forces each `grid-stack-item ` to fill the width of the containing Bootstrap column, owing to the device's resolution exactly matching that of the `media` query.

I've fixed it in my app by loading some extra CSS after your file to force the items to the width I need, but thought I'd raise an issue just in case it needs addressing.

`@media (max-width:768px) {
	.grid-stack-item {
		width: 77px !important;
	}
}`

**Comment by radiolips** [comment]
I'm not sure that this is a bug. Currently in the code, a width of 768 is, by default, considered oneColumnMode. We could make a change in the code so that 767 and below is oneColumnMode, but currently we're using 768. You may override the minWidth value so that 768 still counts as normal mode, but you'll also need to roll your own additional CSS, which you have done here.

If there's some issue with what I'm saying, or if what I'm saying is incorrect, please feel free to reopen.

**Comment by radiolips** [comment]
We decided this answer wasn't good enough, so we implemented a new method for `v.0.2.7`. Please take a look at the changes in the readme in master - you can now set whatever width you want, no CSS media selector required :)

**Comment by Skulmuk** [comment]
Thanks, will give it a try and come back to you if I hit any issues, otherwise, thanks for looking at it :)
