### ISSUE TITLE
Knockout demo and dynamic column change on window stretch event

### ISSUE THREAD

**Issue by crashnick16** [troolee/gridstack.js#45]
Hi,

I think the work that was done for this project so far is amazing and it would be good to have a demo on how this library can be used using knockout. Also, with regards to bootstrap it would be nice to have some kind of more elaborate layout when the window width/height is changed.

What I mean by that is if you have 3 column widget layout on stretching the layout  will change to 2 columns and 1 column at the end....this would be really cool...

**Comment by crashnick16** [comment]
The example that was provided for knockout integration does not work. Just tried it and i get an error that says after render cannot be used in virtual elements. Is the lib supposed to have a custom binding for this issue?

**Comment by troolee** [comment]
Hi,

That knockout sample from the README file is actually how I'm using it. I'm going to prepare a demo page a little bit later.

Which version of knockout.js do you use? Can you share your code?

About layout stretching: grid is collapsed into one column if width is less than 768px. I don't think that I can implement any other variants because there should be a formula how to translate coordinates from 12 columns grid to 6 columns and back and forth.

**Comment by crashnick16** [comment]
I am using knockout 3.2 and I register the grids tack as a ko component along with the widgets.

I did not manage to get the grid loaded at all. Moreover in the readme demo the class grid-stack-item-content is not included.

Also, can this be loved using a require.js shim?

**Comment by crashnick16** [comment]
I got really confused now :(. A demo would be really appreciated :p

**Comment by troolee** [comment]
Will do demo shortly.

**Comment by crashnick16** [comment]
Thanks so much

**Comment by crashnick16** [comment]
i emailed you a demo with the knockout stuff I was working on. I would appreciate if you could have a look...Thanks

**Comment by troolee** [comment]
Hi,

Please check out the README file. I've made fixes of knockout.js sample + added a working example.

**Comment by crashnick16** [comment]
Thanks
