### ISSUE TITLE
Need some clarity on the dimensions of widths and heights

### ISSUE THREAD

**Issue by armensg** [troolee/gridstack.js#487]
The documentation talks about settings widths and heights of grids and grid items but this is very unclear. What are the units of all these numbers? if values are not specified what are the defaults, etc..

For example, how can I go about making my grid items have a width equal to the width of its contents?

**Comment by radiolips** [comment]
Hi, @armensg ! Thanks for the question.

gridstack.js is meant to follow the bootstrap paradigm, which is to say that the widths are in fractions of the whole, ranging from 1-12 (so to make a widget half of the page, its width should be six). Height depends purely on what `cellHeight` is set to.

This answers your original question, I think, but your final question is a bit trickier. Unfortunately, at this time, there is no automatic way to change the width and height of the cells straight from the library. However, you can write code that will adjust the width and height as necessary.

I'm closing this out because your questions should be answered. If you still have questions that I may be of help answering, please feel free to reopen the ticket.
