### ISSUE TITLE
responsive widget behavior

### ISSUE THREAD

**Issue by stolenricecakes** [troolee/gridstack.js#579]
I'm looking to add some responsive-ish behavior to widgets in a grid.   For example:  If a widget is resized to a grid width of 6, I'd like an element to be shown in my widget, but if it is resized to a grid width of 3 I'd like that element to be hidden.   

Is there anything within gridstack that I can leverage to achieve this when building grid widgets?   Ideally, I'm looking for something like bootstrap's grid system that's based on the grid instead of on device width.

**Comment by radiolips** [comment]
@stolenricecakes This feature doesn't exist currently. It's actually tricky because of the different sizes (ie make this six columns if the screen size is small). However, you can write some very simple CSS to accomplish this. `data-gs-width` will be set to 6, so you can set the CSS based on this. Hope this helps!
