### ISSUE TITLE
Gridstack with jquery 1.7 - 2

### ISSUE THREAD

**Issue by AK1979** [troolee/gridstack.js#612]
Hi

I’m using JS frame work (SAPUI5) that works only with jquery 1.7 – 2.0 .
Is it possible to work with gridstack with the above versions ?
Is there any known critical bugs related to the versions using jquery 1.7 – 2 ?

Any alternatives ? 

Thanks,
Arie.

**Comment by radiolips** [comment]
Hey, Arie! There shouldn't be any issue using older jQuery. The primary use of jQuery is to allow for jquery-ui (in addition to some other simple functions). Make sure that you're using a version of jquery-ui that is compatible with your version of jQuery, but otherwise you'll probably be okay. Give it a shot and report back!

**Comment by AK1979** [comment]
Thanks, will check it out.
 Is it OK to use underscore.js instead of lodash.js  ?
Saw it in Stack Overflow but not in the documentation.
Great library!

**Comment by radiolips** [comment]
Thanks! If memory serves, you can use underscore instead of lodash. We're actually only using lodash for a few things and plan on completely removing the dependency soon.
