### ISSUE TITLE
Uncaught TypeError: (0 , _jquery2.default)(...).gridstack is not a function

### ISSUE THREAD

**Issue by nerdess** [troolee/gridstack.js#618]
trying to get gridstack to work with the "official" react boilerplate [create-react-app](https://github.com/facebookincubator/create-react-app) but are failing:

<img width="638" alt="bildschirmfoto 2017-03-20 um 11 12 07" src="https://cloud.githubusercontent.com/assets/711925/24095592/2d489d20-0d5e-11e7-8ae9-139f97fe327c.png">

any hints welcome!

**Comment by nerdess** [comment]
did a bit more investigation, this line is failing inside react-gridstack/lib/grid-stack.js:

` _jquery2 = _interopRequireDefault(_jquery);`

it sets _jquery2 to be an empty object so then of course the initialisation of gridstack is not working...

**Comment by radiolips** [comment]
@nerdess I know you're going to hate this response, but you're going to need to get in touch with @pitrho or whoever is supporting `react-gridstack`. I don't know offhand of a reason why there should be a problem. Maybe there's an issue with using newer jQuery. At the moment, we aren't directly supporting react, so we don't have the resources to look into this for you.

I'm going to close this, but because other people may be having the same issue, I encourage you to report back here with an update.
