### ISSUE TITLE
Resize handle looks wrong on IE9

### ISSUE THREAD

**Issue by Jeff17Robbins** [troolee/gridstack.js#63]
I circled in red the resize handle icon on IE9.  It looks like (maybe?) a rotation that fails on IE9?

![image](https://cloud.githubusercontent.com/assets/2102919/6097213/250d89e0-af82-11e4-9621-5d6e0c32f503.png)

**Comment by ascendantofrain** [comment]
Viewing this in IE9 document mode in IE11 I do not see this issue but then again I am emulating IE9.

**Comment by Jeff17Robbins** [comment]
You can get a free, temporary VM with real IE9 on it at
https://www.modern.ie/en-us/virtualization-tools#downloads

**Comment by troolee** [comment]
It should be fine now.

**Comment by Jeff17Robbins** [comment]
Yes, it displays correctly now on IE9 -- thanks!

**Comment by cvillemure** [comment]
![gridstackresizehandlestillbrokenie9](https://cloud.githubusercontent.com/assets/2197250/10375218/3aa1e45c-6dc5-11e5-9f64-79651bd836fc.png)

As you can see, the handle is still broken in IE9

It seems to be a rendering glitch, since if we move over the icon, the black background disapear :
![gridstackresizehandlestillbrokenie9_renderingglitchs](https://cloud.githubusercontent.com/assets/2197250/10375219/3aa7104e-6dc5-11e5-81f3-32c97c4d72b5.png)
