### ISSUE TITLE
non Responsive in Mobile

### ISSUE THREAD

**Issue by robertwong68** [troolee/gridstack.js#736]
I have arranged the item well on PC and I want to keep the same layout when using mobile. Can I may it non-responsive ?
Thanks.

**Comment by krilllind** [comment]
@robertwong68 You can set the `disableOneColumnMode` to `true` if you don't want a one column layout. Please visit the [dosc](https://github.com/troolee/gridstack.js/tree/develop/doc) before posting an issue.

**Comment by blandman** [comment]
I have been trying to use `disableOneColumnMode` without any luck. Could there be issues with the implementation? I'm using [Ember-Gridstack](https://github.com/yahoo/ember-gridstack).

**Comment by leapit** [comment]
When i set one column,the widgets in mobile view will not keep the same order with pc view,and disableOneColumnMode = true,that's ok. why name the feature as "disableOneColumnMode",a little strange @krilllind @radiolips

**Comment by krilllind** [comment]
@leapit That's because by default the grid will rearrange the items to flow in one line (or column) so that a user can view all items in an easy way by scrolling down. But if you do not like this behaviour you can choose to set `disableOneColumnMode` to `true` and then the items will keep their position.

**Comment by leapit** [comment]
@krilllind thanks,got it.
