### ISSUE TITLE
Sub-divide columns (items - .grid-stack-item) as we can do in Bootstrap 3.x

### ISSUE THREAD

**Issue by MohammedAbdulMateen** [troolee/gridstack.js#742]
Hi! @troolee, @radiolips,

There is a particular division that can be done in Bootstrap 3 to sub-divide a particular column into exact divisions for e.g. Let's say we have two columns col-md-9 and col-md-3

we can sub divide col-md-9 (considering it as col-md-12) into two col-md-6 as shown in the below fiddle

[https://jsfiddle.net/ypfochko/4/](https://jsfiddle.net/ypfochko/4/)

but if we have to use 3 different columns instead of sub-division we could only go like col-md-5, col-md-4 and col-md-3 (where 1st and 2nd columns won't get exact division/width)

I've cases where I need to do different subdivisions like that in the layout, for e.g. in the given below fiddle the 'News And Updates' item should take 25% of the width that can be done using data-gs-width="3" and the remaining two items should have sub-divisions let's say each should occupy 50% in the value of data-gs-width="9"
[https://jsfiddle.net/ypfochko/5/](https://jsfiddle.net/ypfochko/5/)

How can I achieve this [https://jsfiddle.net/ypfochko/4/](https://jsfiddle.net/ypfochko/4/) layout design through gridstack.js, please suggest

Thanks,
Abdul Mateen

**Comment by radiolips** [comment]
@MohammedAbdulMateen I believe your initial example is incorrect. From what I understand of bootstrap, 
```
  <div class="col-md-9">
    <div class="col-md-6">```
^ is not correct because there should be a `class="row"` instead of it to clear.

Either way, I don't understand the question. Widgets are allowed to have 12 columns of space, and the 12 columns are determined by their parent container. You can give it smaller, child container if you don't want the 12 columns to fill a larger container.

Please reopen with more information if you're still having problems.
